name: EconomyPlus
main: ImagicalGamer\EconomyPlus\Main
version: 0.1.3
api: [1.0.0, 2.0.0, 3.0.0]
author: ImagicalGamer
commands:
    addmoney:
        description: EconomyPlus AddMoney!
    bal:
        description: EconomyPlus Balance Command!
    pay:
        description: EconomyPlus Pay Command!
    takemoney:
        description: EconomyPlus TakeMoney Command!
    sellhand:
        description: EconomyPlus SellHand Command!
    factory:
        description: EconomyPlus Factory Command!
    payme:
        description: EconomyPlus PayMe Command!
    debt:
        description: EconomyPlus Debt Command!
    redeem:
        description: EconomyPlus Redeem Command!
    slots:
        description: EconomyPlus Slots Command!
