---
# EconomyPlus Config File

# Money a player starts out with
Default-Money: 1000

# Money someone earns when they kill another player
Death-Money: 200

# Default Language EconomyPlus Uses!
# Avalible Languages: "eng" or "english", "fre" or "french", "ger" or "german", "chi" or "chinese", "schi" or "simplified chinese"
Default-Lang: "eng"

# Enable Commands
bal-Command: true
addmoney-Command: true
takemoney-Command: true
pay-Command: true
topmoney-Command: true

# Enable EconomyPlus Shop!
EnableShop: true
# Shop Format:
# [Shop]
# ItemId
# Ammount
# Price

# Enable EconomyPlus Sell!
EnableSell: true
# Sell Format:
# [Sell]
# ItemId
# Ammount
# Price

#Enable EconomyPlus PermissionShop!
EnablePermShop: true
# Format:
# [Perm]
# Price
# Perm
# Perm

# Current Version DO NOT CHANGE!
Version: 0.1.5
...
